### ISSUE TITLE
unknown import assembly_script_function_exists when deploying on testnet18

### ISSUE THREAD

**Issue by lilyanB** [massalabs/massa-eth-bridge#4]
I want to deploy my SC in innonet.
when I run "npm run deploy" I have this error:
![image](https://user-images.githubusercontent.com/91454320/219697626-8ed2d93c-0184-4b52-88e3-08e43189f037.png)

```shell
> my-massa-sc@0.0.1 deploy
> npm run build && ts-node src/deploy.ts

> my-massa-sc@0.0.1 build /home/lilyan/projects/massa-eth-bridge/Massa/smart-contract
> npx massa-as-compile

2 files to compile
contract to compile assembly/contracts/run.ts

contract to compile assembly/contracts/main.ts

Wallet Address: A16eDqJHyZWQfhNq7xUbyqMMMjb1iKfqQy9p91uTCqY1xkUTC7k has balance (candidate, final) = (81557726.310985776, 81557708.010985776) MAS
Sending operation with 0 MAS coins...
Operation successfully submitted with id: O1aj2G29Geco6frTQbX2vK6mFPpwZkPLGUyeNGD4ufShohgqw3n
Waiting for events...
Awaiting FINAL transaction status....
Transaction with Operation ID O1aj2G29Geco6frTQbX2vK6mFPpwZkPLGUyeNGD4ufShohgqw3n has reached finality!
Deployment success with events: 
{"massa_execution_error":"Runtime error: runtime error when executing operation O1aj2G29Geco6frTQbX2vK6mFPpwZkPLGUyeNGD4ufShohgqw3n: Runtime error: bytecode execution error: Error while importing \"massa\".\"assembly_script_function_exists\": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [I32] })"}
```

I rework my project and I followed this message but I always have the same error :
https://discord.com/channels/761151090673844244/930339655918968872/1074252553270874122

Thanks

**Comment by Thykof** [comment]
Hi @lilyanB could you specify on which network you deploy? JSON_RPC_URL_PUBLIC in the .env file

**Comment by lilyanB** [comment]
in inno net : https://inno.massa.net/test18

**Comment by Thykof** [comment]
ok so this is why. all the tools versions you are using in package-lock.json are meant to work on testnet19. 

assembly_script_function_exists has been renamed in testnet19

either use testnet19, innonet19, or a local sandbox node https://docs.massa.net/en/latest/web3-dev/dummy-network-generation.html (it is a bit outdated so feel free to open an issue on https://github.com/massalabs/massa-docs/issues and even fix it ;) I can help you on that!)
