### ISSUE TITLE
Unable to start the massa web3 client

### ISSUE THREAD

**Issue by lilyanB** [massalabs/massa-eth-bridge#7]
I can't initiate my Massa Web3 Client. I am using inno net 19 but I get the same problem when I try with the default client.
Before, everything worked. Then I updated "@massalabs/massa-web3" because of this PR was merged:
https://github.com/massalabs/massa-web3/pull/111

Since then I can't initiate the Mass-Web3 Client in my file:
https://github.com/massalabs/massa-eth-bridge/blob/main/Massa/front/src/App.tsx#L43

In my front I have thie error:
![image](https://user-images.githubusercontent.com/91454320/221138469-e09e36d3-0d53-4a96-bab7-e5b030429889.png)

```console
Access to XMLHttpRequest at 'https://inno.massa.net/test19' from origin 'http://localhost:5173' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.
```
```console
retryExecuteFunction.ts:28 Failed to execute function bound sendJsonRPCRequest. Retrying for 1th time in 1s.
```
```console
POST https://inno.massa.net/test19 net::ERR_FAILED
```

**Comment by gregLibert** [comment]
@lilyanB @BatiGencho Maybe it's due to the reinstallation of the testnet19.
Can you do a request by hand without using massa web3 to confirm ?

**Comment by lilyanB** [comment]
@gregLibert With postmann I do a POST request on (https://test.massa.net/api/v2) : 
![image](https://user-images.githubusercontent.com/91454320/221156194-8ff3dcf9-1d16-413f-9f8e-d860ac5a7e47.png)

**Comment by BatiGencho** [comment]
@gregLibert @lilyanB Its not that, its axios. I have fixed the issue and am preparing a new release asap. Will let yo uknw once its out.

**Comment by BatiGencho** [comment]
It is due to this bug: https://github.com/axios/axios/issues/5262

**Comment by lilyanB** [comment]
ok, thank you
